### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by ubamrein** [DP-3T/dp3t-sdk-backend#59]
We need to update documentation. 
Here is a collection of issues related to that. As far as we do not close this issue here, please provide documentation feedback in this issue.

- [x] `Getting org.flywaydb.core.api.FlywayException when I try to run Docker` https://github.com/DP-3T/dp3t-sdk-backend/issues/50
- [x] `Clarification on "batchReleaseTime"` https://github.com/DP-3T/dp3t-sdk-backend/issues/49
-  [x] `Add Documentation on how the JWT profile works` https://github.com/DP-3T/dp3t-sdk-backend/issues/43
- [x] `API Roadmap` https://github.com/DP-3T/dp3t-sdk-backend/issues/42
- [x] `Dates clarification`  https://github.com/DP-3T/dp3t-sdk-backend/issues/21
- [x] `Data Model / Concept Questions` https://github.com/DP-3T/dp3t-sdk-backend/issues/4
- [x] `Glossary` https://github.com/DP-3T/dp3t-sdk-backend/issues/3

**Comment by Vanuan** [comment]
Here's some diagram to think about dates:
![Test and trace Development Board (5)](https://user-images.githubusercontent.com/361985/80477898-63ee2b80-8955-11ea-8f93-92a3fba96b79.jpg)

**Comment by Vanuan** [comment]
Also, swagger seems to be outdated. It looks like there's been a switch to use protobuf instead of JSON?

**Comment by AndreasHuber-CH** [comment]
Concerning swagger, I found two yaml files at different versions of the API:
One at https://github.com/DP-3T/dp3t-sdk-backend/blob/develop/documentation/yaml/sdk.yaml, which is also referenced in the README.
It contains most REST paths, but it does not indicate the correct content-type for all of them, and the swagger editor also prints out some errors. It would be nice to have an update of this file.
Also having better descriptions for the different APIs and the request/response bodies would be appreciated.

And then there is another one here:
https://github.com/DP-3T/dp3t-sdk-backend/blob/develop/dpppt-backend-sdk/dpppt-backend-sdk-ws/generated/swagger/swagger.yaml
I think this one could be deleted to avoid any confusion.

**Comment by ubamrein** [comment]
We currently think that it might be better to add documentation on the overall architecture and design in a centralised repository. 

In this readme, we try to only include build, run and code specific stuff, whereas in the central repo we would add glossary, information on the Gapple approach, definitions of the terms used and so on.

What is your opinion on that?

**Comment by AndreasHuber-CH** [comment]
So sdk.yaml will not contain any description of the APIs. That's ok for me.
But at least sdk.yaml should be updated to contain all APIs, so that people that click on the swagger editor link in the readme can try out the full api. (right now the /v1/buckets/{dayDateStr} is missing for example)

**Comment by ubamrein** [comment]
It's been a while, but we updated swagger documentation, tried (or are trying) to simplify controller logic, and added comments to important parts of the code. 

There are also some major refactoring in progress, which will be merged soon to develop. 
- [Removes logic from the controller](https://github.com/DP-3T/dp3t-sdk-backend/tree/feature/insert-manager)
- [Ensures no still valid key is returned in SQL](https://github.com/DP-3T/dp3t-sdk-backend/tree/feature/get-exposed-sql-filters)
- [Unify time handling and clarify the use of time](https://github.com/DP-3T/dp3t-sdk-backend/pull/201)

If you feel like something needs to be addressed again, please feel free to open a new issue again!
